### ISSUE TITLE
$_COOKIE in LEMP doesn't contain all browser's cookie

### ISSUE THREAD

**Issue by Daisuke-sama** [lando/lemp#13]

**Comment by labboy0276** [comment]
@Daisuke-sama can you tell me how you are setting your cookies in code please.

**Comment by Daisuke-sama** [comment]
sure, that's a call like that
```
setcookie("current_user_id", $user_id, $expire_time, $path);
setcookie("current_user_key", $permission_key, $expire_time, $path);
```

**Comment by labboy0276** [comment]
Seems pretty normal.  Can I see your `.lando.yml` file as well @Daisuke-sama

**Comment by Daisuke-sama** [comment]
```
name: crm-web
recipe: lemp
config:
  php: 7.4
  xdebug: "debug,develop"
services:
  appserver:
#    webroot: /var/www/html/crm-stroy
    app_mount: delegated
    build_as_root:
      - "apt -y update && apt-get install -y gnupg2 && echo 'deb https://apt.postgresql.org/pub/repos/apt/ stretch-pgdg main' >> /etc/apt/sources.list.d/pgdg.list && wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add - && apt -y update && apt-get install -y postgresql-client-12"
      - rm -f /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && pkill -o -USR2 php-fpm
    run:
      - test -f /var/www/html && rm /var/www/html
      - ln -s /app /var/www/html
      - test -f ./crm-stroy && rm ./crm-stroy
      - ln -s /app ./crm-stroy
    xdebug: true
    overrides:
      environment:
        APP_ENV: "local"
        XDEBUG_CONFIG: "client_host=host.docker.internal discover_client_host=1 log=/tmp/xdebug.log remote_enable=true remote_host=host.docker.internal client_port=9003 idekey=PHPSTORM"
  database:
    type: postgres:12
    portforward: 54321
    creds:
      database: ---
events:
  post-rebuild:
    - database: psql --version
    - database: psql -h database -U postgres -c "CREATE USER --- WITH ENCRYPTED PASSWORD '---' SUPERUSER;"
    - database: psql -h database -U postgres -c "GRANT ALL PRIVILEGES ON DATABASE --- TO ---;"
    - database: pg_restore -h database -U postgres -w -d --- /app/_dev/---db-2022-01-17.dump
tooling:
  xdebug-on:
    service: appserver
    description: Enable xdebug for nginx.
    cmd: rm -f /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && docker-php-ext-enable xdebug && pkill -o -USR2 php-fpm && echo "Xdebug enabled"
    user: root
  xdebug-off:
    service: appserver
    description: Disable xdebug for nginx.
    cmd: rm -f /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && pkill -o -USR2 php-fpm && echo "Xdebug disabled"
    user: root

```
