### ISSUE TITLE
Lando LEMP recipe installs incorrect Composer version

### ISSUE THREAD

**Issue by Niyabi** [lando/lemp#2]
In my .lando.yml file I set Composer to be version 2.0.7 however 'lando composer -V' shows version 1.10.1. I've tried rebuilds, upgraded lando to version 3.4.2, set composer version in service... no matter what I've tried it's still version 1.10.1. I'm working in WSL Ubuntu (20.04).

```yml
recipe: lemp
config:
  webroot: docroot/pub
  php: '7.4'
  database: mariadb:10.4
  xdebug: 'false'
  composer_version: '2.0.7'
  config:
    php: config/php.ini
    vhosts: config/nginx.conf
```
