### ISSUE TITLE
Image devwithlando/php:8.2-fpm-5 missing composer

### ISSUE THREAD

**Issue by mdevrees** [lando/lemp#65]
Hi,

When I run a `lando start` or a `lando rebuild-y` my app container gets started/rebuilt and in the build logs it says it cannot install composer:
```
$ /bin/sh: 1: /etc/lando/service/helpers/install-composer.sh: not found
```

My lando file looks as follows:

```yaml
name: 'project'
recipe: 'lemp'
config:
  webroot: 'pub'
  database: 'mariadb:10.4'
  composer_version: false
  config:
    vhosts: '.lando/config/nginx/default.conf'
    php: '.lando/config/php/php.ini'
    database: '.lando/config/mariadb/my.cnf'
services:
  appserver:
    type: 'php:8.2'
    via: nginx
    scanner: false
    composer_version: 2.2.24
    build_as_root:
      - 'apt-get -qq update -y'
      - 'apt-get -qq install jq libxslt-dev cron vim -y'
      - 'docker-php-ext-install sockets xsl'
```

Is this an issue in the image? Should I define the composer_version on the `config` scope and not in the `services` scope?

Update: Moving `composer_version` to the `config` scope did not make a difference.
